server:
  port: 8003

mybatis:
  type-aliases-package: com.lbb.springcloud.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: microservicecloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.89:3306/clouddb03
    username: oyj
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-provider8003 #修改注册到eureka的服务名称
    prefer-ip-address: true #访问路径显示ip地址

info:
  app.name: xinwis-microservicecloud
  company.name: www.xinwis.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
